### ISSUE TITLE
Android Usecase

### ISSUE THREAD

**Issue by BlackSwallow96** [Aeron/ikev2-strongswan-vpn#11]
hi there ...
how can i get ca certificates from docker to install it on android devices ?
or how can i use this configurations on android ?
in android vpn connection manager i got this error : 
unsuccessful , not secure 

i guess if i can install related ca certifications i can use it on andorid .
thanks

**Comment by Aeron** [comment]
There is a native application for Android called [strongSwan](https://play.google.com/store/apps/details?id=org.strongswan.android), but it doesn’t support PSK authorization for some reason. And that’s the only authorization mechanism my configuration currently supports. It doesn’t use any certificates.

I have a (private) branch with EAP-TLS support, but it’s still work-in-progress. So, until it’s merged back to the main branch, don’t consider it stable, even if you managed to find an image with the `tls` tag 😉

And I’m afraid I don’t have any timeline for it yet. I don’t have any Android devices around me, so it’s not my priority right now. But if I deliver it, I must be sure it works with all primary platforms. So, yeah, someday, maybe.

**Comment by BlackSwallow96** [comment]
oh yeah that's right .
okey no problem i will wait for new version ... 

thanks for your reply
best regards
